
namespace MarketLensSoftware
{
    partial class LoginForm
    {
     
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        //Code above is automatically generated by VS 
        #region 
        //Declaration of form components below
        
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoginForm));
            this.TitleText = new System.Windows.Forms.Label();
            this.UsernameLabel = new System.Windows.Forms.Label();
            this.PswrdLabel = new System.Windows.Forms.Label();
            this.ContinueLabel = new System.Windows.Forms.Button();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.createaccountlink = new System.Windows.Forms.Label();
            this.UsernameText = new System.Windows.Forms.TextBox();
            this.PasswordText = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // TitleText
            // 
            this.TitleText.AutoSize = true;
            this.TitleText.BackColor = System.Drawing.Color.Transparent;
            this.TitleText.Font = new System.Drawing.Font("Impact", 39.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TitleText.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.TitleText.Location = new System.Drawing.Point(87, 26);
            this.TitleText.Name = "TitleText";
            this.TitleText.Size = new System.Drawing.Size(154, 65);
            this.TitleText.TabIndex = 0;
            this.TitleText.Text = "Log In";
            // 
            // UsernameLabel
            // 
            this.UsernameLabel.AutoSize = true;
            this.UsernameLabel.BackColor = System.Drawing.Color.Transparent;
            this.UsernameLabel.Font = new System.Drawing.Font("Lucida Sans Unicode", 14F);
            this.UsernameLabel.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.UsernameLabel.Location = new System.Drawing.Point(20, 155);
            this.UsernameLabel.Name = "UsernameLabel";
            this.UsernameLabel.Size = new System.Drawing.Size(104, 23);
            this.UsernameLabel.TabIndex = 3;
            this.UsernameLabel.Text = "Username";
            // 
            // PswrdLabel
            // 
            this.PswrdLabel.AutoSize = true;
            this.PswrdLabel.BackColor = System.Drawing.Color.Transparent;
            this.PswrdLabel.Font = new System.Drawing.Font("Lucida Sans Unicode", 14F);
            this.PswrdLabel.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.PswrdLabel.Location = new System.Drawing.Point(25, 254);
            this.PswrdLabel.Name = "PswrdLabel";
            this.PswrdLabel.Size = new System.Drawing.Size(99, 23);
            this.PswrdLabel.TabIndex = 4;
            this.PswrdLabel.Text = "Password";
            // 
            // ContinueLabel
            // 
            this.ContinueLabel.BackColor = System.Drawing.Color.Lavender;
            this.ContinueLabel.Cursor = System.Windows.Forms.Cursors.Default;
            this.ContinueLabel.FlatAppearance.BorderColor = System.Drawing.Color.White;
            this.ContinueLabel.FlatAppearance.BorderSize = 2;
            this.ContinueLabel.FlatAppearance.MouseDownBackColor = System.Drawing.Color.WhiteSmoke;
            this.ContinueLabel.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Black;
            this.ContinueLabel.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.ContinueLabel.Font = new System.Drawing.Font("Impact", 18F);
            this.ContinueLabel.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.ContinueLabel.Location = new System.Drawing.Point(12, 395);
            this.ContinueLabel.Name = "ContinueLabel";
            this.ContinueLabel.Size = new System.Drawing.Size(328, 43);
            this.ContinueLabel.TabIndex = 5;
            this.ContinueLabel.Text = "Continue";
            this.ContinueLabel.UseVisualStyleBackColor = false;
            this.ContinueLabel.Click += new System.EventHandler(this.ContinueLabel_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.AliceBlue;
            this.pictureBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pictureBox1.BackgroundImage")));
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.pictureBox1.Location = new System.Drawing.Point(19, 190);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(44, 45);
            this.pictureBox1.TabIndex = 6;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.panel2.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.panel2.Location = new System.Drawing.Point(24, 234);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(316, 1);
            this.panel2.TabIndex = 0;
            // 
            // pictureBox2
            // 
            this.pictureBox2.BackColor = System.Drawing.Color.White;
            this.pictureBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pictureBox2.BackgroundImage")));
            this.pictureBox2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox2.Location = new System.Drawing.Point(18, 273);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(45, 42);
            this.pictureBox2.TabIndex = 6;
            this.pictureBox2.TabStop = false;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.SystemColors.ControlDarkDark;
            this.panel1.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.panel1.Location = new System.Drawing.Point(24, 321);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(316, 1);
            this.panel1.TabIndex = 0;
            // 
            // createaccountlink
            // 
            this.createaccountlink.AutoSize = true;
            this.createaccountlink.Font = new System.Drawing.Font("Impact", 16F);
            this.createaccountlink.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.createaccountlink.Location = new System.Drawing.Point(189, 349);
            this.createaccountlink.Name = "createaccountlink";
            this.createaccountlink.Size = new System.Drawing.Size(151, 27);
            this.createaccountlink.TabIndex = 7;
            this.createaccountlink.Text = "Create Account";
            this.createaccountlink.Click += new System.EventHandler(this.CreateAccount_Click);
            // 
            // UsernameText
            // 
            this.UsernameText.BackColor = System.Drawing.Color.LightGray;
            this.UsernameText.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.UsernameText.Font = new System.Drawing.Font("Lucida Bright", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UsernameText.Location = new System.Drawing.Point(69, 199);
            this.UsernameText.Name = "UsernameText";
            this.UsernameText.Size = new System.Drawing.Size(271, 29);
            this.UsernameText.TabIndex = 8;
            // 
            // PasswordText
            // 
            this.PasswordText.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.PasswordText.Font = new System.Drawing.Font("Lucida Bright", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PasswordText.Location = new System.Drawing.Point(69, 280);
            this.PasswordText.Name = "PasswordText";
            this.PasswordText.Size = new System.Drawing.Size(271, 29);
            this.PasswordText.TabIndex = 9;
            this.PasswordText.UseSystemPasswordChar = true;
            // 
            // LoginForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.SystemColors.InfoText;
            this.ClientSize = new System.Drawing.Size(359, 450);
            this.Controls.Add(this.PasswordText);
            this.Controls.Add(this.UsernameText);
            this.Controls.Add(this.createaccountlink);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.ContinueLabel);
            this.Controls.Add(this.PswrdLabel);
            this.Controls.Add(this.UsernameLabel);
            this.Controls.Add(this.TitleText);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "LoginForm";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.LoginForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label TitleText;
        private System.Windows.Forms.Label UsernameLabel;
        private System.Windows.Forms.Label PswrdLabel;
        private System.Windows.Forms.Button ContinueLabel;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label createaccountlink;
        private System.Windows.Forms.TextBox UsernameText;
        private System.Windows.Forms.TextBox PasswordText;
    }
}

