//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketLensSoftware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CSProjDBEntities : DbContext
    {
        public CSProjDBEntities()
            : base("name=CSProjDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GOOGL> GOOGLs { get; set; }
        public virtual DbSet<MSFT> MSFTs { get; set; }
        public virtual DbSet<NVDA> NVDAs { get; set; }
    
        public virtual ObjectResult<GetDate_Result> GetDate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDate_Result>("GetDate");
        }
    }
}
